import fs from "node:fs";
import path from "node:path";
import { SkillLoader } from "./load.js";
import { SkillPaths } from "./paths.js";
import type { SkillDefinition } from "./types.js";

export class SkillSync {
  private readonly loader = new SkillLoader();

  run(): { skillCount: number; outPath: string } {
    const skills = this.loader.loadAllSkillDefinitions();
    const source = this.renderGeneratedModule(skills);
    fs.mkdirSync(path.dirname(SkillPaths.GENERATED_SKILLS_PATH), {
      recursive: true,
    });
    fs.writeFileSync(SkillPaths.GENERATED_SKILLS_PATH, source, "utf8");
    return {
      skillCount: skills.length,
      outPath: SkillPaths.GENERATED_SKILLS_PATH,
    };
  }

  private renderGeneratedModule(skills: SkillDefinition[]): string {
    const lines: string[] = [
      "// AUTO-GENERATED by `npm run skill-sync`. Do not edit by hand.",
      "",
      'import type { SkillDefinition } from "../skills/types.js";',
      "",
      `export const skills: SkillDefinition[] = ${this.stringify(skills)};`,
      "",
      "export const skillsById: Record<string, SkillDefinition> = Object.fromEntries(",
      "  skills.map((skill) => [skill.id, skill]),",
      ");",
      "",
      "export const alwaysAttachedSkills: SkillDefinition[] = skills.filter(",
      '  (skill) => skill.metadata.attachType === "always",',
      ");",
      "",
    ];

    return lines.join("\n");
  }

  private stringify(value: unknown): string {
    return JSON.stringify(value, null, 2);
  }
}
