import fs from "node:fs";
import path from "node:path";
import PDFDocument from "pdfkit";

function slugify(text: string): string {
  const slug = text
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
  return slug.length > 0 ? slug : "document";
}

const outDir = process.argv[2];
const text = process.argv.slice(3).join(" ").trim();

if (!outDir || !text) {
  console.error("usage: create-pdf.ts <outdir> <text...>");
  process.exit(1);
}

fs.mkdirSync(outDir, { recursive: true });
const outPath = path.join(outDir, `${slugify(text)}.pdf`);

const doc = new PDFDocument({ margin: 50 });
const stream = fs.createWriteStream(outPath);
doc.pipe(stream);

doc.fontSize(12).text(text, { align: "left" });

const footer = "generated by AI";
doc.fontSize(9).fillColor("#444444");
doc.text(footer, 50, doc.page.height - 50, {
  lineBreak: false,
  align: "left",
});

doc.end();

await new Promise<void>((resolve, reject) => {
  stream.on("finish", () => resolve());
  stream.on("error", reject);
});

console.log(outPath);
