#!/usr/bin/env python3
"""Create a PDF from text using pymupdf. Footer (left): generated by AI."""

from __future__ import annotations

import re
import sys
from pathlib import Path

import pymupdf as fitz


def slugify(text: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", text.strip().lower()).strip("-")[:60]
    return slug or "document"


def main() -> None:
    if len(sys.argv) < 3:
        print("usage: create-pdf.py <outdir> <text...>", file=sys.stderr)
        sys.exit(1)

    out_dir = Path(sys.argv[1])
    text = " ".join(sys.argv[2:]).strip()
    if not text:
        print("usage: create-pdf.py <outdir> <text...>", file=sys.stderr)
        sys.exit(1)

    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{slugify(text)}.pdf"

    doc = fitz.open()
    page = doc.new_page()
    margin = 50
    rect = fitz.Rect(margin, margin, page.rect.width - margin, page.rect.height - 70)
    page.insert_textbox(rect, text, fontsize=12, align=fitz.TEXT_ALIGN_LEFT)

    footer = "generated by AI"
    page.insert_text(
        fitz.Point(margin, page.rect.height - 40),
        footer,
        fontsize=9,
        color=(0.27, 0.27, 0.27),
    )

    doc.save(out_path)
    doc.close()
    print(out_path)


if __name__ == "__main__":
    main()
